archived_personal_projects=(
  allocation-component
  fizz-buzz-component
  obsidian-account-component
  release-control
  todo
)

personal_projects=(
  actor
  gpg
  number-serialization
  pyleglight
  office-electronics
  os-config
  terminal-colors
  terminal-output-styling
  work-logs
  zephyrus-g14-linux
)

test_bench_projects=(
  test-bench
  test-bench-1.x
  test-bench-bootstrap
  test-bench-example
  test-bench-fixture
  test-bench.software
)
