set -o vi

setPrompt() {
	local esc reset background red green yellow blue magenta cyan foreground resetColor user resetUser hostname resetHostname branch resetBranch noBranch resetNoBranch directory resetDirectory displayGitBranch

	esc="\033"

	reset="$esc[0m"

	background="$esc[30m"
	red="$esc[31m"
	green="$esc[32m"
	yellow="$esc[33m"
	blue="$esc[34m"
	magenta="$esc[35m"
	cyan="$esc[36m"
	foreground="$esc[37m"
	resetColor="$esc[39m"

	user=$blue
	resetUser=$resetColor

	hostname=$cyan
	resetHostname=$resetColor

	branch=$green
	resetBranch=$resetColor
	noBranch="$esc[2;39m"
	resetNoBranch="$esc[0m"

	directory=$yellow
	resetDirectory=$resetColor

	displayGitBranch="(git symbolic-ref --quiet --short HEAD 2>/dev/null || echo -e \"${noBranch}(none)${resetNoBranch}\") | awk \"{ print \\\"(Branch: ${branch}\\\" \\\$0 \\\"${resetBranch})\\\" }\""

	export PS1="${reset}[${user}\u${resetUser}@${hostname}\h${resetHostname}] \$(${displayGitBranch}) ${directory}\w${resetDirectory}\n> "
}

setAliases() {
	alias less="less -R"
	alias ls="ls --color"

	alias copy-settings="for example in settings/*.example; do cp -v \$example settings/\$(basename \$example .example); done"

	alias rb="ruby --disable-gems --disable-did_you_mean --enable-frozen-string-literal"

	alias pg-start="sudo systemctl start postgresql"
	alias pg-stop="sudo systemctl stop postgresql"
	alias pg-status="sudo systemctl status postgresql"
	alias pgup="pg-start"
	alias pgdown="pg-stop"

	alias redis-start="sudo systemctl start redis-server"
	alias redis-stop="sudo systemctl stop redis-server"
	alias redis-status="sudo systemctl status redis-server"
	alias redisup="redis-start"
	alias redisdown="redis-stop"

	alias refresh-gems="rm -rf Gemfile.lock gems .bundle && ./install-gems.sh"
}

setEditor() {
	export EDITOR=vim
}

activateCompletion() {
	for script in ~/.bash/completion/*; do
		set +eu
		source $script
		set -eu
	done
}

activateColorTheme() {
  set +eu

	source ~/.bash/color_theme.bash

  set -eu
}

set -eu

setPrompt
setAliases
setEditor
activateCompletion
activateColorTheme

set +eu

if [ ! -s ~/.bashrc.local ]; then
	touch ~/.bashrc.local
fi

source ~/.bashrc.local
