source ~/.bashrc

set -o vi

printPrompt() {
	local esc reset

	esc="\033"

	relativePath=$(dirs)
	absolutePath=$PWD

	echo -e -n "$esc[0m$esc[1;33m$relativePath$esc[22;39m"

	if [ $relativePath != $absolutePath ]; then
		echo -e -n " $esc[2;3m($absolutePath)$esc[22;23m"
	fi

	echo -e "\n> "
}

setPrompt() {
	export PS1="\$(printPrompt)"
}

setAliases() {
	alias less="less -R"
	alias ls="ls --color"

	alias copy-settings="for example in settings/*.example; do cp -v \$example settings/\$(basename \$example .example); done"

  alias copy="xsel --clipboard --input"
  alias paste="xsel --clipboard --output"

	alias rb="ruby --disable-gems --disable-did_you_mean --enable-frozen-string-literal"

	alias pg-start="sudo systemctl start postgresql"
	alias pg-stop="sudo systemctl stop postgresql"
	alias pg-status="sudo systemctl status postgresql"
	alias pgup="pg-start"
	alias pgdown="pg-stop"

	alias redis-start="sudo systemctl start redis-server"
	alias redis-stop="sudo systemctl stop redis-server"
	alias redis-status="sudo systemctl status redis-server"
	alias redisup="redis-start"
	alias redisdown="redis-stop"

	alias refresh-gems="rm -rf Gemfile.lock gems .bundle && ./install-gems.sh"

	alias tS="tmux new -s"
	alias trd="tmux attach-session -t"
	alias tpair="test -S /tmp/pair && tmux -S /tmp/pair attach-session || tmux -S /tmp/pair new -s pair"
}

setEditor() {
	export EDITOR=vim
}

activateCompletion() {
	for script in ~/.bash/completion/*; do
		set +eu
		source $script
		set -eu
	done
}

setPrompt
unset -f setPrompt

setAliases
unset -f setAliases

setEditor
unset -f setEditor

activateCompletion
unset -f activateCompletion

set +eu

if [ -s ~/.bash_profile.local ]; then
  source ~/.bash_profile.local
fi
