runtime bundle/vim-pathogen/autoload/pathogen.vim

call pathogen#infect()

runtime plugin/matchit.vim
runtime plugin/rename.vim

set nocompatible

" Display
set t_Co=256
let base16colorspace=256
syntax on
set number

" File management
set nobackup
set noswapfile
filetype on
filetype indent on
filetype plugin on

" Split panes
set splitbelow
set splitright

" Search
set nohlsearch
set incsearch

" Indentation/formatting
set autoindent
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set smarttab
set nowrap

" Command line (Ctrl-F)
set wildmode=longest,list

" Shell
set shell=bash\ --login

" Spell checking
set spelllang=en_us
set nospell

" Status line
set laststatus=2 " Always show status bar
set statusline=  " Reset status bar

set statusline+=%f%M\ " File name
set statusline+=\[%{strlen(&ft)?&ft:'none'}] " File type
set statusline+=%= " Remainder is right aligned
set statusline+=\ \Buffer:\ %-3.3n " Buffer number

source ~/.vim/keyboard_shortcuts.vim
source ~/.vim/file_types.vim

if filereadable(glob("~/.vim/vimrc.local"))
  source ~/.vim/vimrc.local
endif

" Override theme-specific handling of spelling and capitalization errors
let &t_Cs="\e[4:3;58:5:1m"
let &t_Ce="\e[4:0;59m"
hi SpellBad ctermbg=NONE
hi SpellCap ctermbg=NONE
