#!/usr/bin/env bash

set -eu

source $(dirname $BASH_SOURCE)/git-functions.bash

dependency git-verify-initial-commit

function git-verify-branch() {
  head=${1:-master}

  git-verify-initial-commit $head

  $git filter-branch \
    --tag-name-filter cat \
    --tree-filter \
    './test.sh >/dev/null && echo -e "\e[32mPass\e[39m" || echo -e "\e[31mFail\e[39m"' $head
}

export git-verify-branch $@
