#!/usr/bin/env bash

set -eu

source $(dirname $BASH_SOURCE)/git-functions.bash

dependency git-verify-initial-commit

function git-topic-start() {
  name=$1
  parentHead=${2:-HEAD}

  git-verify-initial-commit $parentHead

  parentCommit=$($git rev-parse $parentHead)

  branchCount=$($git show-ref --heads | grep $parentCommit | wc -l)

  if [ $branchCount = '0' ]; then
    $git branch $name $parentCommit || exit 1
    echo "Started topic \`$name' at $parentCommit"

  elif [ $branchCount = '1' ]; then
    treeID=$($git show --format=%T $parentCommit)

    emptyCommit=$($git commit-tree $treeID -p $parentCommit < /dev/null)

    $git branch $name $emptyCommit || exit 1
    echo "Started topic \`$name' at $emptyCommit"

  else
    exec >&2

    echo "Error: topic parent at $parentHead would be ambiguous (Branch Count: $branchCount)"
  fi
}

export git-topic-start $@
