#!/usr/bin/env bash

set -eu

source $(dirname $BASH_SOURCE)/git-functions.bash

function git-verify-initial-commit() {
  ref=${1:-HEAD}

  if ! $git rev-parse --quiet HEAD 2>/dev/null >&2; then
    exec >&2

    echo "Error: \`$ref' is not a reference (has an initial commit been added yet?)"

    exit 1
  fi
}

export git-verify-initial-commit $@
